name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Bun
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: bun install && bun run build
      - name: Prettier
        run: prettier --write .
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=greenenwald
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
